import SearchLayout from "@/_component/Search-layout";
import Head from "next/head";
import { ReactNode, useEffect, useState } from "react";
import classes from "./home.module.scss";
import movieDummy from "@/dummy.json";
import { MovieData } from "../../type/moive";
import MovieItem from "@/_component/movie-item";
import { useQuery } from "@tanstack/react-query";
import { QueryKey } from "../../type/querykey";

export default function Home() {
  const [recommendMoive, setRecommendMovie] = useState<MovieData[]>([]);

  const {
    data: moveDatas,
    isLoading,
    isSuccess,
  } = useQuery<MovieData[]>({
    queryKey: [QueryKey.search],
    queryFn: () => movieDummy,
  });

  useEffect(() => {
    if (isSuccess) {
      setRecommendMovie(moveDatas.slice(0, 3) || []);
    }
  }, [moveDatas, isSuccess]);

  if (isLoading) {
    return <>Loading....</>;
  }

  if (moveDatas) {
    return (
      <>
        <Head>
          <title>한입 시네마</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>

        <section className={classes.section}>
          <h3>지금 가장 추천하는 영화</h3>
          <div className={classes.recommendedMovies}>
            {recommendMoive.map((e: MovieData, key) => (
              <MovieItem {...e} key={`movie-${key}`} />
            ))}
          </div>
        </section>

        <section className={classes.section}>
          <h3>등록된 모든 영화</h3>
          <div className={classes.movielist}>
            {moveDatas.map((e: MovieData, key) => (
              <MovieItem {...e} key={`movie-${key}`} />
            ))}
          </div>
        </section>
      </>
    );
  }
}

Home.globalLayout = (page: ReactNode) => {
  return <SearchLayout>{page}</SearchLayout>;
};
